{% set name = "ipfn" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ipfn-{{ version }}.tar.gz
  sha256: bf6b446f9dea53e28481a5cff9461769cba5711542eaebe05e554ac09c832ddd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - pandas >=0.22.0
    - python >={{ python_min }}

test:
  source_files:
    - tests
  imports:
    - ipfn
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests/tests.py
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/Dirguis/ipfn.git
  summary: Iterative Proportional Fitting with N dimensions, for python
  license: MIT
  license_file: licence.txt

extra:
  recipe-maintainers:
    - thewchan
